### ISSUE TITLE
About memory

### ISSUE THREAD

**Issue by WenchaoD** [kzjeef/SSLunarDate#1]
Hey, there. 
    You Chinese? I used this framework in my calendar view, to show the lunar day string for every 'day', but it needs to create a lot of SSLunarDate instance, and the scrolling performance seems pleasant . Could you give me a few pointers about how to optimize this performance?

**Comment by kzjeef** [comment]
Yes, I'm Chinese.

About the performance, do you cache the NSCalendar object ? you'd better avoid create this object by [NSCalendar defaultCalendar] in your loop.

Better create this object once, and pass it into SSLunarDate.

**Comment by WenchaoD** [comment]
Gread idea, thanks a lot

**Comment by WenchaoD** [comment]
@kzjeef 
    Hello，我尝试了只用一个NSCalendar对象，但是在真机iPhone5 8.1系统上还是略有卡顿，我用UICollectionview创建日历，每页42个格子，除了当月的天数其余的是上个月和下个月的。每天下面摆着农历。如果我把农历的部分去掉全部改成“123”，卡顿就不见了，但是改成[[SSLunarDate alloc] initWithDate:Calendar] ，然后把缓存的Calendar也传进去，还是会卡顿。有没有什么办法直接计算农历而不用创建SSLunarDate对象呢?
    这是我正在尝试写的分支 https://github.com/f33chobits/FSCalendar/tree/collectionview-subtitution-branch

**Comment by kzjeef** [comment]
是这样的。 本身计算农历是需要时间的。 如果你担心的是alloc带来的 分配内存的开销， 你可以在计算的循环里面加一个autoreleaspool （就像main那样）， 但是我觉得更多的开销是来自于计算农历本身的开销，而不是分配内存。

**Comment by WenchaoD** [comment]
嗯，我也发现了，不是内存分配的问题。这个库很快了，我还用了别的库，慢的没法看。
