### ISSUE TITLE
你好，请问(LibLunarContext *) lunar是什么样的参数？请教如何将nsdate转化为这个参数。

### ISSUE THREAD

**Issue by donjixote** [kzjeef/SSLunarDate#3]
- (NSString *) getLunarHolidayNameForDate: (LibLunarContext *) lunar region:(SSHolidayRegion) region
  我目前想用这个函数判断当前的日期是否是节日，并显示。但是并不知道这个LibLunarContext的lunar该怎么获取。求指教。

**Comment by kzjeef** [comment]
你看一下SSLunarDate.m 的代码, 那里面有创建这个 context 的代码, 单独用只要那样用就行.
